name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint with ruff
        run: ruff app tests

      - name: Type check with mypy
        run: mypy app

      - name: Security scan with bandit
        run: bandit -r app -c bandit.yaml

      - name: Run tests
        run: pytest tests
q